// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Usernowhasvarcharlimitations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Usernowhasvarcharlimitations));
        
        string IMigrationMetadata.Id
        {
            get { return "201610070110342_User now has varchar limitations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
